config/routes.rb
Rails.application.routes.draw do

  resources :exercises do
    collection do
      get 'most_recent_with_name'
      get 'names'
    end
    resources :exercise_sets
  end

  resources :workouts, shallow: true do
    resources :exercises, :cardios
  end

  resources :exercise_sets, :cardios

  root 'spa#index'

  get ':controller/:action/:id'

end

app/models/workout.rb
class Workout < ActiveRecord::Base
  has_many :exercises,  -> { order 'sort_order ASC' }, dependent: :destroy
  has_many :cardios, dependent: :destroy

  validates_presence_of :workout_date
  validates_associated :exercises

  def to_builder
    Jbuilder.new do |b|
      b.extract! self, :id, :workout_date, :time_started, :time_ended, :split_name, :notes, :updated_at, :created_at
      b.exercises do
        b.array!(exercises.map{|e| e.to_builder })
      end
      #b.exercises(exercises.map{|e| e.to_builder })
      b.cardios(cardios.map{|c| c.to_builder })
    end
  end

  def previous_workout
    @previous_workout ||= Workout.where('workout_date < ?', self.workout_date).order(:workout_date, :desc).first
  end

  def next_workout
    @next_workout ||= Workout.where('workout_date > ?', self.workout_date).order(:workout_date).first
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :set_workout, only: %i[show edit update destroy]

  # GET /workouts
  # GET /workouts.json
  def index
    @workouts = Workout.all
  end

  # GET /workouts/1
  # GET /workouts/1.json
  def show; end

  # GET /workouts/new
  def new
    @workout = Workout.new
  end

  # GET /workouts/1/edit
  def edit; end

  # POST /workouts
  # POST /workouts.json
  def create
    @workout = Workout.new(workout_params)

    respond_to do |format|
      if @workout.save
        format.html { redirect_to @workout, notice: 'Workout was successfully created.' }
        format.json { render :show, status: :created, location: @workout }
      else
        format.html { render :new }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workouts/1
  # PATCH/PUT /workouts/1.json
  def update
    respond_to do |format|
      if @workout.update(workout_params)
        format.html { redirect_to @workout, notice: 'Workout was successfully updated.' }
        format.json { render :show, status: :ok, location: @workout }
      else
        format.html { render :edit }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workouts/1
  # DELETE /workouts/1.json
  def destroy
    @workout.destroy
    respond_to do |format|
      format.html { redirect_to workouts_url, notice: 'Workout was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_workout
    query = Workout
    if params[:full]
      query = query.includes(:cardios, exercises: [:exercise_sets])
    end
    @workout = query.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def workout_params
    params.require(:workout).permit(:workout_date, :time_started, :time_ended, :split_name, :notes)
  end
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/workouts/_form.html.haml
= form_for @workout do |f|
  - if @workout.errors.any?
    #error_explanation
      %h2= "#{pluralize(@workout.errors.count, "error")} prohibited this workout from being saved:"
      %ul
        - @workout.errors.full_messages.each do |message|
          %li= message

  .form-group
    = f.label :workout_date
    = f.date_select :workout_date
  .form-group
    = f.label :time_started
    = f.time_select :time_started
  .form-group
    = f.label :time_ended
    = f.time_select :time_ended
  .form-group
    = f.label :split_name
    = f.text_field :split_name
  .form-group
    = f.label :notes
    = f.text_area :notes
  .actions
    -#= f.submit 'Save'
    = button_tag 'Save', :class => 'btn btn-default'

app/views/workouts/edit.html.haml
%h1 Editing workout

= render 'form'

= link_to 'Show', @workout
\|
= link_to 'Back', workouts_path

app/views/workouts/index.html.haml
%h1 Listing workouts

%table.table
  %thead
    %tr
      %th Date
      %th Time Started
      %th Time Ended
      %th Split Name
      %th Notes
      %th
      %th
      %th

  %tbody
    - @workouts.each do |workout|
      %tr
        %td= workout.workout_date
        %td= workout.time_started
        %td= workout.time_ended
        %td= workout.split_name
        %td= workout.notes
        %td= link_to 'Show', workout
        %td= link_to 'Edit', edit_workout_path(workout)
        %td= link_to 'Destroy', workout, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Workout', new_workout_path

app/views/workouts/new.html.haml
%h1 New workout

= render 'form'

= link_to 'Back', workouts_path

app/views/workouts/show.html.haml
%p#notice= notice

%p
  %b Workout Date:
  = @workout.workout_date

%p
  %b Time Stated:
  = @workout.time_started
%p
  %b Time Ended:
  = @workout.time_ended
%p
  %b Split name:
  = @workout.split_name
%p
  %b Notes:
  = @workout.notes

.panel.panel-default
  .panel-heading
    %h3.panel-title Exercises
  .panel-body
    %ul
      - @workout.exercises.each do |ex|
        %li[ex]
          = ex.name
    %button.btn.btn-default.pull-right
      %span.glyphicon.glyphicon-plus
      Add Exercise


= link_to 'Edit', edit_workout_path(@workout)
\|
= link_to 'Back', workouts_path