config/routes.rb
Rails.application.routes.draw do

  resources :exercises do
    collection do
      get 'most_recent_with_name'
      get 'names'
    end
    resources :exercise_sets
  end

  resources :workouts, shallow: true do
    resources :exercises, :cardios
  end

  resources :exercise_sets, :cardios

  root 'spa#index'

  get ':controller/:action/:id'

end

app/models/cardio.rb
class Cardio < ActiveRecord::Base
  belongs_to :workout

  validates :name, :duration, :resistance_level, :distance, presence: true
  validates :duration, :resistance_level, :distance, numericality: { greater_than_or_equal_to: 0 }
  validates :calories, numericality: { greater_than_or_equal_to: 0, allow_nil: true }

  def to_builder
    Jbuilder.new do |b|
      b.extract! self, :id, :name, :duration, :resistance_level, :distance, :calories, :updated_at, :created_at
    end
  end
end

app/controllers/cardios_controller.rb
class CardiosController < ApplicationController
  before_action :set_cardio, only: [:show, :edit, :update, :destroy]

  # GET /cardios
  # GET /cardios.json
  def index
    @cardios = Cardio.all
  end

  # GET /cardios/1
  # GET /cardios/1.json
  def show
  end

  # GET /cardios/new
  def new
    @cardio = Cardio.new
  end

  # GET /cardios/1/edit
  def edit
  end

  # POST /cardios
  # POST /cardios.json
  def create
    @cardio = Cardio.new(cardio_params)

    respond_to do |format|
      if @cardio.save
        format.html { redirect_to @cardio, notice: 'Cardio was successfully created.' }
        format.json { render :show, status: :created, location: @cardio }
      else
        format.html { render :new }
        format.json { render json: @cardio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cardios/1
  # PATCH/PUT /cardios/1.json
  def update
    respond_to do |format|
      if @cardio.update(cardio_params)
        format.html { redirect_to @cardio, notice: 'Cardio was successfully updated.' }
        format.json { render :show, status: :ok, location: @cardio }
      else
        format.html { render :edit }
        format.json { render json: @cardio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cardios/1
  # DELETE /cardios/1.json
  def destroy
    @cardio.destroy
    respond_to do |format|
      format.html { redirect_to cardios_url, notice: 'Cardio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cardio
      @cardio = Cardio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cardio_params
      params.require(:cardio).permit(:name, :duration, :resistance_level, :notes, :distance, :calories, :workout_id)
    end
end

app/helpers/cardios_helper.rb
module CardiosHelper
end

app/views/cardios/_form.html.haml
= form_for @cardio do |f|
  - if @cardio.errors.any?
    #error_explanation
      %h2= "#{pluralize(@cardio.errors.count, "error")} prohibited this cardio from being saved:"
      %ul
        - @cardio.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :duration
    = f.number_field :duration
  .field
    = f.label :resistance_level
    = f.number_field :resistance_level
  .field
    = f.label :notes
    = f.text_area :notes
  .field
    = f.label :distance
    = f.text_field :distance
  .field
    = f.label :calories
    = f.text_field :calories
  .field
    = f.label :workout
    = f.text_field :workout
  .actions
    = f.submit 'Save'

app/views/cardios/edit.html.haml
%h1 Editing cardio

= render 'form'

= link_to 'Show', @cardio
\|
= link_to 'Back', cardios_path

app/views/cardios/index.html.haml
%h1 Listing cardios

%table
  %thead
    %tr
      %th Name
      %th Duration
      %th Resistance level
      %th Notes
      %th Distance
      %th Calories
      %th Workout
      %th
      %th
      %th

  %tbody
    - @cardios.each do |cardio|
      %tr
        %td= cardio.name
        %td= cardio.duration
        %td= cardio.resistance_level
        %td= cardio.notes
        %td= cardio.distance
        %td= cardio.calories
        %td= cardio.workout
        %td= link_to 'Show', cardio
        %td= link_to 'Edit', edit_cardio_path(cardio)
        %td= link_to 'Destroy', cardio, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Cardio', new_cardio_path

app/views/cardios/new.html.haml
%h1 New cardio

= render 'form'

= link_to 'Back', cardios_path

app/views/cardios/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @cardio.name
%p
  %b Duration:
  = @cardio.duration
%p
  %b Resistance level:
  = @cardio.resistance_level
%p
  %b Notes:
  = @cardio.notes
%p
  %b Distance:
  = @cardio.distance
%p
  %b Calories:
  = @cardio.calories
%p
  %b Workout:
  = @cardio.workout

= link_to 'Edit', edit_cardio_path(@cardio)
\|
= link_to 'Back', cardios_path