config/routes.rb
Rails.application.routes.draw do

  resources :exercises do
    collection do
      get 'most_recent_with_name'
      get 'names'
    end
    resources :exercise_sets
  end

  resources :workouts, shallow: true do
    resources :exercises, :cardios
  end

  resources :exercise_sets, :cardios

  root 'spa#index'

  get ':controller/:action/:id'

end

app/models/exercise_set.rb
class ExerciseSet < ActiveRecord::Base
  belongs_to :exercise

  validates_presence_of :exercise, :reps, :sort_order
  validates_numericality_of :reps, :sort_order
  validates_numericality_of :weight, :target_reps, allow_nil: true

  validate :validate_sort_order

  before_validation :ensure_sort_order_has_value

  def validate_sort_order
    if sort_order.present? && exercise_id.present? && ExerciseSet.where(exercise_id: exercise_id, sort_order: sort_order).exists?
      errors.add(:sort_order, "must be unique for given exercise_id")
    end
  end

  def ensure_sort_order_has_value
    #self.sort_order ||= ExerciseSet.where(exercise_id: exercise_id).maximum(:sort_order) + 1
    if new_record? && sort_order.blank?
      self.sort_order ||= (ExerciseSet.where(exercise_id: self.exercise_id).maximum(:sort_order) || 0) + 1
    end
  end

  def to_builder
    Jbuilder.new do |b|
      b.extract! self, :id, :reps, :target_reps, :weight, :notes, :sort_order, :updated_at, :created_at
    end
  end

end

app/controllers/exercise_sets_controller.rb
class ExerciseSetsController < ApplicationController
  before_action :set_exercise_set, only: [:show, :edit, :update, :destroy]

  # GET /exercise_sets
  # GET /exercise_sets.json
  def index
    @exercise_sets = ExerciseSet.all
  end

  # GET /exercise_sets/1
  # GET /exercise_sets/1.json
  def show
  end

  # GET /exercise_sets/new
  def new
    @exercise_set = ExerciseSet.new
  end

  # GET /exercise_sets/1/edit
  def edit
  end

  # POST /exercise_sets
  # POST /exercise_sets.json
  def create
    @exercise_set = ExerciseSet.new(exercise_set_params)

    respond_to do |format|
      if @exercise_set.save
        format.html { redirect_to @exercise_set, notice: 'Exercise set was successfully created.' }
        format.json { render :show, status: :created, location: @exercise_set }
      else
        format.html { render :new }
        format.json { render json: @exercise_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exercise_sets/1
  # PATCH/PUT /exercise_sets/1.json
  def update
    respond_to do |format|
      if @exercise_set.update(exercise_set_params)
        format.html { redirect_to @exercise_set, notice: 'Exercise set was successfully updated.' }
        format.json { render :show, status: :ok, location: @exercise_set }
      else
        format.html { render :edit }
        format.json { render json: @exercise_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exercise_sets/1
  # DELETE /exercise_sets/1.json
  def destroy
    @exercise_set.destroy
    respond_to do |format|
      format.html { redirect_to exercise_sets_url, notice: 'Exercise set was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exercise_set
      @exercise_set = ExerciseSet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exercise_set_params
      params.require(:exercise_set).permit(:weight, :reps, :target_reps, :notes, :exercise_id)
    end
end

app/helpers/exercise_sets_helper.rb
module ExerciseSetsHelper
end

app/views/exercise_sets/_form.html.haml
= form_for @exercise_set do |f|
  - if @exercise_set.errors.any?
    #error_explanation
      %h2= "#{pluralize(@exercise_set.errors.count, "error")} prohibited this exercise_set from being saved:"
      %ul
        - @exercise_set.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :weight
    = f.text_field :weight
  .field
    = f.label :reps
    = f.text_field :reps
  .field
    = f.label :target_reps
    = f.text_field :target_reps
  .field
    = f.label :notes
    = f.text_area :notes
  .field
    = f.label :exercise
    = f.text_field :exercise
  .actions
    = f.submit 'Save'

app/views/exercise_sets/edit.html.haml
%h1 Editing exercise_set

= render 'form'

= link_to 'Show', @exercise_set
\|
= link_to 'Back', exercise_sets_path

app/views/exercise_sets/index.html.haml
%h1 Listing exercise_sets

%table
  %thead
    %tr
      %th Weight
      %th Reps
      %th Target reps
      %th Notes
      %th Exercise
      %th
      %th
      %th

  %tbody
    - @exercise_sets.each do |exercise_set|
      %tr
        %td= exercise_set.weight
        %td= exercise_set.reps
        %td= exercise_set.target_reps
        %td= exercise_set.notes
        %td= exercise_set.exercise
        %td= link_to 'Show', exercise_set
        %td= link_to 'Edit', edit_exercise_set_path(exercise_set)
        %td= link_to 'Destroy', exercise_set, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Exercise set', new_exercise_set_path

app/views/exercise_sets/new.html.haml
%h1 New exercise_set

= render 'form'

= link_to 'Back', exercise_sets_path

app/views/exercise_sets/show.html.haml
%p#notice= notice

%p
  %b Weight:
  = @exercise_set.weight
%p
  %b Reps:
  = @exercise_set.reps
%p
  %b Target reps:
  = @exercise_set.target_reps
%p
  %b Notes:
  = @exercise_set.notes
%p
  %b Exercise:
  = @exercise_set.exercise

= link_to 'Edit', edit_exercise_set_path(@exercise_set)
\|
= link_to 'Back', exercise_sets_path