config/routes.rb
Rails.application.routes.draw do

  resources :exercises do
    collection do
      get 'most_recent_with_name'
      get 'names'
    end
    resources :exercise_sets
  end

  resources :workouts, shallow: true do
    resources :exercises, :cardios
  end

  resources :exercise_sets, :cardios

  root 'spa#index'

  get ':controller/:action/:id'

end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :set_exercise, only: %i[show edit update destroy]

  # Note: actions :index, :new, :create may be nested under /workouts/:workout_id/exercises

  # GET /exercises
  # GET /exercises.json
  # GET /workout/:workout_id/exercises
  # GET /workout/:workout_id/exercises.json
  def index
    if params[:workout_id].present?
      @workout = Workout.find(params[:workout_id])
      @exercises = @workout.exercises
    else
      @exercises = Exercise.all
    end
  end

  # GET /exercises/1
  # GET /exercises/1.json
  def show; end

  # GET /exercises/new
  # GET /workouts/:workout_id/exercises/new
  def new
    if params[:workout_id].present?
      @workout = Workout.find(params[:workout_id])
      @exercise = @workout.exercises.build
    else
      @exercise = Exercise.new
    end
  end

  # GET /exercises/1/edit
  def edit; end

  # POST /exercises
  # POST /exercises.json
  # POST /workout/:workout_id/exercises
  # POST /workout/:workout_id/exercises.json
  def create
    if params[:workout_id].present?
      @workout = Workout.find(params[:workout_id])
      @exercise = @workout.exercises.build(exercise_params.permit(:name, :notes))
    else
      @exercise = Exercise.new(exercise_params)
    end

    respond_to do |format|
      if @exercise.save
        format.html { redirect_to @exercise, notice: 'Exercise was successfully created.' }
        format.json { render :show, status: :created, location: @exercise }
      else
        format.html { render :new }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exercises/1
  # PATCH/PUT /exercises/1.json
  def update
    respond_to do |format|
      if @exercise.update(exercise_params)
        format.html { redirect_to @exercise, notice: 'Exercise was successfully updated.' }
        format.json { render :show, status: :ok, location: @exercise }
      else
        format.html { render :edit }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exercises/1
  # DELETE /exercises/1.json
  def destroy
    @exercise.destroy
    respond_to do |format|
      format.html { redirect_to exercises_url, notice: 'Exercise was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def names
    @names = Exercise.names
    render json: @names
  end

  def most_recent_with_name
    name = params[:name]
    exclude = params[:exclude]
    @exercise = Exercise.includes(:exercise_sets, :workout).where.not(id: exclude).most_recent_with_name!(name)
    @include_workout = true
    render :show
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_exercise
    src = Exercise
    if params[:full]
      src = Exercise.includes(:exercise_sets, :workout)
    end
    @exercise = src.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def exercise_params
    params.require(:exercise).permit(:name, :notes, :workout_id)
  end

end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/views/exercises/_form.html.haml
= form_for @exercise do |f|
  - if @exercise.errors.any?
    #error_explanation
      %h2= "#{pluralize(@exercise.errors.count, "error")} prohibited this exercise from being saved:"
      %ul
        - @exercise.errors.full_messages.each do |message|
          %li= message

  .form-group
    = f.label :name
    = f.text_field :name
  .form-group
    = f.label :notes
    = f.text_area :notes
  .form-group
    = f.label :workout
    = f.text_field :workout
  .actions
    = f.submit 'Save'

app/views/exercises/_inline_form.html.haml
%li.list-group-item
  %hr.list-group-item-heading
    = inline_form.name

app/views/exercises/edit.html.haml
%h1 Editing exercise

= render 'form'

= link_to 'Show', @exercise
\|
= link_to 'Back', exercises_path

app/views/exercises/index.html.haml
%h1 Listing exercises

%table
  %thead
    %tr
      %th Name
      %th Notes
      %th Workout
      %th
      %th
      %th

  %tbody
    - @exercises.each do |exercise|
      %tr
        %td= exercise.name
        %td= exercise.notes
        %td= exercise.workout
        %td= link_to 'Show', exercise
        %td= link_to 'Edit', edit_exercise_path(exercise)
        %td= link_to 'Destroy', exercise, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Exercise', new_exercise_path

app/views/exercises/new.html.haml
%h1 New exercise

= render 'form'

= link_to 'Back', exercises_path

app/views/exercises/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @exercise.name
%p
  %b Notes:
  = @exercise.notes
%p
  %b Workout:
  = @exercise.workout

= link_to 'Edit', edit_exercise_path(@exercise)
\|
= link_to 'Back', exercises_path